version: "3"

services:

  frontend:
    depends_on:
      - apimock
      - nginx

  apimock:
    build:
      context: ./apimock
    image: apimock-projetinho_daniel
    container_name: apimock-projetinho_daniel
    hostname: apimock-projetinho_daniel
    command: npm run apimock:watch
    network_mode: "host"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./apimock/server:/apimock/server
