# Generated by Django 4.0.5 on 2023-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.URLField(max_length=1024)),
                ('clima', models.CharField(choices=[('Quente', 'Quente'), ('Frio', 'Frio')], max_length=50)),
                ('tipo_turismo', models.CharField(choices=[('Négocios', 'Negocios'), ('Eventos', 'Eventos'), ('Aventura', 'Aventura'), ('Lazer', 'Lazer')], max_length=50)),
            ],
        ),
    ]
