# Generated by Django 4.0.5 on 2023-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrativos',
            name='tipo_turismo',
            field=models.CharField(choices=[('Négocios', 'Negocios'), ('Eventos', 'Eventos'), ('Aventura', 'Aventura'), ('Lazer', 'Lazer'), ('Museu', 'Museu'), ('Natureza', 'Natureza')], max_length=50),
        ),
    ]
